### ISSUE TITLE
rocker pull

### ISSUE THREAD

**Issue by Howardcl** [tlab-wide/AutowareV2X#47]
hello,i want to test your AutowareV2X,but i meeting some trouble in create 2 autoware docker,
in next step,i use :
rocker --nvidia --x11 --user --privileged --volume /home/ubuntu22/autoware_main --volume home/ubuntu22/autoware_map --network=v2x_net --name autoware_1 --oyr-run-arg "--ip 10.0.0.2 --hostname autoware_1" -- ghcr.io/autowarefoundation/autoware-universe:latest-cuda

but download docker image too slow,can you help me?

**Comment by yuasabe** [comment]
@Howardcl 
Thanks for trying out AutowareV2X, and sorry for the delay in response.
As per the [documentation for Autoware](https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/docker-installation-devel/#how-to-set-up-a-workspace), can you try to pull the Docker image with the following command?

```
docker pull ghcr.io/autowarefoundation/autoware-universe:latest-cuda
```

If this is still too slow, maybe I can zip the newest Docker image on my end and put it on Google Drive for example so you can download it from there. But getting the Autoware Docker image with the above command is preferred because it will have all the newest updates included in it.

Let me know how the above command works on your end.

**Comment by Howardcl** [comment]
@yuasabe  Thank you！my problem is sloved now! i can pull docker image by using vpn.
